# Generated by Django 4.0.6 on 2022-07-17 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=45)),
                ('img1', models.ImageField(upload_to='teams')),
                ('desc1', models.TextField()),
            ],
        ),
    ]
